

INSERT INTO BOOK 
(ID,TITLE,AUTHOR,PUBLISHER,PUBLICATION_YEAR)
VALUES
('TestId1','TestTitle1','TestAuthor1','TestPublisher1',2001);

INSERT INTO BOOK 
(ID,TITLE,AUTHOR,PUBLISHER,PUBLICATION_YEAR)
VALUES
('TestId2','TestTitle2','TestAuthor2','TestPublisher2',2002);

INSERT INTO BOOK 
(ID,TITLE,AUTHOR,PUBLISHER,PUBLICATION_YEAR)
VALUES
('TestId3','TestTitle3','TestAuthor3','TestPublisher3',2003);

INSERT INTO BOOK 
(ID,TITLE,AUTHOR,PUBLISHER,PUBLICATION_YEAR)
VALUES
('TestId4','TestTitle4','TestAuthor4','TestPublisher4',2004);

INSERT INTO BOOK 
(ID,TITLE,AUTHOR,PUBLISHER,PUBLICATION_YEAR)
VALUES
('TestEvennId1','TestAnEvenTitle','TestAuthor1','TestPublisher1',2003);

INSERT INTO BOOK 
(ID,TITLE,AUTHOR,PUBLISHER,PUBLICATION_YEAR)
VALUES
('TestEvennId4','TestAnEvenTitle2','TestAuthor1','TestPublisher1',2005);

INSERT INTO BOOK 
(ID,TITLE,AUTHOR,PUBLISHER,PUBLICATION_YEAR)
VALUES
('TestEvenId2','TestAnOddTitle','TestAuthor2','TestPublisher2',2002);

INSERT INTO BOOK 
(ID,TITLE,AUTHOR,PUBLISHER,PUBLICATION_YEAR)
VALUES
('TestEvenId3','TestAnEvenTitleMoreVowels','TestAuthor3','TestPublisher3',2001);

INSERT INTO CURRENT_STOCK
(ID, TITLE)
VALUES
('TestId1','TestTitle1');

INSERT INTO CURRENT_STOCK
(ID, TITLE)
VALUES
('TestId2','TestTitle2');

INSERT INTO CURRENT_STOCK
(ID, TITLE)
VALUES
('TestId3','TestTitle3');